色々と追加
takanakahiko/discord-tts pull request #11
Opened 2021-04-02 07:43 UTC by atomu21263

@mentionかprefixでの呼び出しをswitch
コメントアウトの追加
@mentionでの反応がなかったため修正
起動: go run main.go -call (mention|prefix{任意}) -token <bot_token> -id <client_id>
prefixについて... @mention joinなどだったのが{任意} joinで呼び出せるように(起動時に設定) !ttsでも?joinでも反応するはず(呼び出すときにエスケープしないといけないかもしれない)

2021-04-02 07:44 UTC, atomu21263 commented
もしかしてやらかした?

2021-04-04 17:40 UTC, takanakahiko requested changes
ご提案ありがとうございます！感謝です！

インデントが 4 から 2 になっていたのが気になりました。
基本的に GoLang の推奨インデントは 4 なので、それに合わしていただけると嬉しいです！

あと他にも気になった点をレビューしたのでご確認ください。

また、一度に複数の変更があると、レビューや修正の手間が増えてしまうかなと思うので、PullRequestの内容はなるべくシンプルに(たとえば、まずは prefix の実装のみ)していただけると、お互いにスムーズに進められると思います！

2021-04-04 17:40 UTC, takanakahiko commented on main.go
> +  id = flag.String("id", "", "bot client id")
環境変数のままにしていただけると嬉しいです！
コマンドライン引数にするメリットがあまりなさそうなのですが、どうでしょうか？

2021-04-04 17:40 UTC, takanakahiko commented on main.go
>  }
Goの推奨される書き方に則りたいので早期リターンしてくれると嬉しいです。

例えばこんな感じ。

```go
 func botName() string {
  if (*call_type == "mention") {
    return "<@" + clientID() + ">"
  }
  return *call_type
}
```

2021-04-04 17:40 UTC, takanakahiko commented on main.go
> +  if vcsession == nil {
switch case の中で VC 接続の判定をする(というかもともとの書き方だと)とスッキリすると思いました。
基本的に、正しくないコマンドの使い方をされたときに「コマンドがない」ではなく「コマンドがエラー内容を返す」ほうがユーザーにとってわかりやすいのかなと思いました。

```
switch {
  case strings.HasPrefix(m.Content, botName()+" join"):
    if vcsession != nil {
      sendMessage(discord, m.ChannelID, "Bot is already in voice-chat.")
      return
    }
    ....
  case strings.HasPrefix(m.Content, botName()+" leave"):
     ...
}
```

2021-04-05 04:01 UTC, atomu21263 commented on main.go
> +  id = flag.String("id", "", "bot client id")
環境変数だと既に設定したのかがわかりずらいっていうのと
明確にデータを引き渡す為ですね
exportの後なんかの作業してlogが流れたーとか(ないと思うけど) っていうだけなのでflagじゃなくて普通のでもいいかと

2021-04-05 04:02 UTC, atomu21263 commented on main.go
>  }
golangのreturn周りの処理が解らなかったので... returnした瞬間に処理終わるのか... 直します

2021-04-06 18:53 UTC, takanakahiko commented
すみません、推奨されるインデントは半角スペース4つではなくハードタブですね。失礼しました。

2021-04-08 14:39 UTC, atomu21263 commented
tabだと実際に動かしてる環境からコピペしたときに半角４つに変わっちゃう...

2021-04-12 12:14 UTC, takanakahiko commented
手元に Git 環境を作っている感じではなく、GitHub 上にコピペしている感じですかね？
手元に Git をインストールして、手元で Tab を利用すれば正しく動く気がします！

2021-04-12 14:35 UTC, atomu21263 commented
よくわからない...
コードはこんな感じで行けますかね?

2021-04-17 07:35 UTC, takanakahiko commented
手元でGitコマンドを用いていますでしょうか？
そうでなければ、ここらへんを参考に作業してみるとうまくいくと思います。
http://urusulambda.com/2019/02/03/github%E3%81%AEpullrequest%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E9%80%81%E3%82%8A%E6%96%B9/

そうですね、まずPullRequestの内容はなるべくシンプルに(たとえば、まずは prefix の実装のみ)していただけると、お互いにスムーズに進められると思います！

2021-04-17 07:35 UTC, takanakahiko commented
このPRは一度閉じた上で、新しいPRで小さな変更に取り組んでみるとかどうでしょうか

2021-04-17 10:37 UTC, atomu21263 commented
ということなのでclose

2021-04-17 10:37 UTC, closed without merging